<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.effectivejava</groupId>
        <artifactId>hands-on-effective-java</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>refactored-solutions</artifactId>
    <name>Refactored Solutions</name>
    <description>YOUR refactored implementations go here</description>

    <dependencies>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10.1</version>
        </dependency>
    </dependencies>
</project>
